### ISSUE TITLE
looking for New York (1983) font

### ISSUE THREAD

**Issue by fernan** [JohnDDuncanIII/ClassicMacintoshFonts#4]
Hi John! 

I came across this repo, seems like a nice resource compiling a good deal of history of Apple Fonts. I am looking for the old New York Apple typeface https://en.wikipedia.org/wiki/New_York_(1983_typeface), which is not the same as the 2019 one (https://en.wikipedia.org/wiki/New_York_(2019_typeface). 

The latter is available for Developers from Apple: https://developer.apple.com/fonts/, I am looking for the TrueType 1983 version of New York developed by Susan Kare. 

I've been able to look into the *.dfont files you have here: 
```NewYork_15.dfont  NewYork_17.dfont  NewYork_21.dfont  NewYork_22.dfont  NewYork_26.dfont```

But upon converting them to .ttf using fondu in Ubuntu/Linux, and inspecting them with FontForge they seem to be the old bitmap versions pre-dating MacOS 7. 
```
# this is on windows wsl - ubuntu 
sudo apt install fondu
fondu NewYork_15.dfont
# produces NewYork_15.ttf
```
This is how they loook in FontForge: 
![image](https://github.com/JohnDDuncanIII/macfonts/assets/175475/b1b9b5f8-7f1a-4feb-b4e6-c018d27ff84b)

I have browsed your repo and couldn't find other instances of New York fonts for Mac OS 7 through 9, do you carry these in this repo? Otherwise do you have any pointers on where to look? 

thanks in advance -- fernan

**Comment by JohnDDuncanIII** [comment]
Hi @fernan. The bitmap conversions for New York are stored in https://github.com/JohnDDuncanIII/macfonts/tree/master/Macintosh%20OS%201-6/OS%20X.

I think you're looking for https://github.com/JohnDDuncanIII/macfonts/blob/master/Macintosh%20OS%209/New%20York.

Due to Github limitations (https://github.com/JohnDDuncanIII/macfonts/issues/3), these resource fork fonts are empty. I've added a TODO to compress + upload the zip to the repo.

For now, please just unzip it directly here: [New York.zip](https://github.com/JohnDDuncanIII/macfonts/files/13316398/New.York.zip). I've included both the resource fork font and the fontforge `.sfd`.

<img width="1353" alt="Screenshot 2023-11-10 at 1 40 10 AM" src="https://github.com/JohnDDuncanIII/macfonts/assets/9257785/691faaf5-a830-4463-a135-f4bb530d6ae3">

<img width="773" alt="Screenshot 2023-11-10 at 1 37 44 AM" src="https://github.com/JohnDDuncanIII/macfonts/assets/9257785/e5d079bc-74f0-4531-a3c9-d202458ccf30">

**Comment by fernan** [comment]
Thanks! That did it! I did find that part of the repo, but as you said I was sent away by the 0 bytes (empty) length of the file. Thanks @JohnDDuncanIII
